### PR TITLE
Update docs for ansible-opendaylight

### PR DESCRIPTION
**Pull request by AkshitaJha**
Signed-off-by: Akshita Jha <zenith158@gmail.com>

### CODE REVIEW

**Comment by AkshitaJha** [comment]
Any other information in the README.md that needs to be added/improved?

**Comment by dfarrell07** [comment]
This looks perfect, thanks @AkshitaJha!

> Any other information in the README.md that needs to be added/improved?

I noticed that the example `extra_feautres` could use an update. 'odl-ovsdb-openstack' is the old-NetVirt feature, to get the post-refactoring/split feature it should be `odl-netvirt-openstack`.

Would also be good to update this from a recent version of ODL (or remove ODL-specific version info to require less maintenance?)

```
opendaylight-user@root>feature:list | grep odl-ovsdb-openstack
odl-ovsdb-openstack | 1.1.0-Lithium | x | ovsdb-1.1.0-Lithium <snip>
```

**Comment by dfarrell07** [comment]
> Any other information in the README.md that needs to be added/improved?

Might also be good to include an example of invoking ansible-playbook to do an install?

**Comment by AkshitaJha** [comment]
> Might also be good to include an example of invoking ansible-playbook to do an install?

Already doing this in the 'Example Playbook' section. Maybe it's better to move it to say an 'Install OpenDaylight` section?

**Comment by dfarrell07** [comment]
> Already doing this in the 'Example Playbook' section. 

Ah, yes, so you are, sorry.

> Maybe it's better to move it to say an 'Install OpenDaylight` section?

Yes, that might be a bit more clear to quickly scan. Up to you.

**Comment by AkshitaJha** [comment]
>  'odl-ovsdb-openstack' is the old-NetVirt feature, to get the post-refactoring/split feature it should be odl-netvirt-openstack.

Updated to odl-netvirt-openstack.

```
opendaylight-user@root>feature:list | grep odl-ovsdb-openstack
odl-ovsdb-openstack | 1.1.0-Lithium | x | ovsdb-1.1.0-Lithium <snip>
```
Removed the ODL version info.

> Ah, yes, so you are, sorry.

Np. :) Added a new section, 'Installing OpenDaylight`

**Comment by dfarrell07** [comment]
Awesome, perfect and ready to merge @AkshitaJha.

**Pull request merged**
